# Generated by Django 4.1.3 on 2022-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/None/no-img.png', upload_to='products'),
        ),
    ]
